### ISSUE TITLE
Confused about what and how

### ISSUE THREAD

**Issue by kblomqvist** [xcdl/xcdl-go#1]
I see that you have very similar ideas, though much experienced, what I have about the build system, source file packaging and sharing. However, I'm not able to understand how to use these tools. I see that there is a deprecated Python version of the CLI-tool followed by Node.js version, which is going to be replaced by a Go version (hopefully being the release version)? Why Python version was deprecated? Is there something you can do in Go what's not in Node or Python? Have you checked [Click](https://github.com/pallets/click) for Python? For instance, I used Click to create a CLI-tool to generate "header files" for Cortex-M in Rust from the given CMSIS SVD-file. This use case is now part of the unit tests of my code generator tool called [yasha](https://github.com/kblomqvist/yasha).

You have written good amount of helpful instructions and there's plenty of references given, but still I'm missing easy step-by-step CLI usage, for example how to get uOS++ _"installed"_ from xPacks.

**Comment by ilg-ul** [comment]
> Why Python version was deprecated?

it's a long story. in the first version, the configuration files were Python scripts. this was very convenient for a prototyping version, but had a major disadvantage, the configuration files were not easily modifiable by a program.

the next version of XCDL will use two kind of files: configuration files in json (written by the tools, not by hand), and scripts, written in JavaScript (written by hand).

although executing JavaScript code in Go is possible, it is by far less convenient than in node.js, so, after long considerations, I decided to stick to node.js.

> click ... pasha

thank you for the hint, I'll take a look.

if you are interested in contributing to the design/development of xcdl, you are more than welcome.

> how to get uOS++ "installed" from xPacks

until the xcdl tool will be functional, please check the shell scripts currently used in the [demo projects](https://github.com/micro-os-plus/eclipse-demo-projects)

**Comment by kblomqvist** [comment]
I managed to get sources via xPacks by using the `generate.sh` script found under the demo projects:

```bash
git clone https://github.com/micro-os-plus/eclipse-demo-projects.git
cd eclipse-demo-projects/f4discovery-blinky-micro-os-plus/scripts
bash generate.sh
```

To work with xPacks directly with scripts from https://github.com/xpacks/scripts was not successful.

After running the _generate.sh_ I managed to import the project into Eclipse (import source being General/Existing Project into Workspace). By right clicking the project I chose _Build Project_ and Eclipse started building the project even though I had no glue how it knew how to build it. Are the build instructions part of the Eclipse project file? I didn't find any _"make-file"_. Is it plan to include build instructions into xPacks so that one can build from command-line, e.g. using Make/CMake/SCons?

At the end, the build was not successful and there were couple of errors, likely because the code takes advance of C++14 and I have only gcc-arm-none-eabi version 4.8 available.

```
os-memory.h:158:58: error: 'max_align_t' is not a member of 'std'
os-memory.h:1670:77: error: 'remove_cv_t' is not a member of 'std'
os-memory.h:1670:94: error: template argument 2 is invalid
os-memory.h:1670:97: error: '::value' has not been declared
```

P.S. I have 64-bit Debian and can't use pre-compiled gcc-arm-none-eabi released in Launchpad. I tried to build it from sources but their `build-*.sh` scripts didn't work for me.

**Comment by ilg-ul** [comment]
could you please relocate this thread to the project forum (https://www.element14.com/community/groups/gnu-arm-eclipse), the xPack/xcdl category?

I would like to remove this project, as there will probably not be any go version, and your question has little to do with go.

**Comment by ilg-ul** [comment]
I already copied and answered your questions there (https://www.element14.com/community/message/209516/l/the-new-experimental-scripts-to-generate-system-code-from-xpacks#209516)

please use this thread for further questions/suggestions, or create new items for different topics.
